name: Jenkins CI PR FE 

on:
  pull_request:
    branches:
      - main
    types: 
        - opened
        - synchronize
        - reopened

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
        - name: Print PR Info (debug)
            run: |
              echo "ğŸ” GitHub Event: ${{ github.event_name }}"
              echo "ğŸ‘¤ PR Author: ${{ github.actor }}"
              echo "ğŸ” Source branch: ${{ github.head_ref }}"
              echo "ğŸ¯ Target branch: ${{ github.base_ref }}"
              echo "ğŸ”— PR URL: ${{ github.event.pull_request.html_url }}"
              
        - name: Trigger Jenkins Job
          run: |
            curl -X POST "http://${{ secrets.JENKINS_IP }}:8080/job/RMIT_Store/buildWithParameters" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
            --data-urlencode "BRANCH_NAME=${{ github.head_ref }}"
    
        - name: Confirm Request Sent
            run: echo "âœ… Jenkins trigger request sent successfully (if credentials and token are correct)."
